<?php
$j = '{"data" : [{"id" : 1,"name" : "用户属性","order" : 1,"data" : [{"id" : 1,"name" : "购物性别","type" : 2,"order" : 1,"data" : [{"labelid" : 1,"labelname" : "购物性别","valueid" : 0,"valuename" : "男","order" : 0},{"labelid" : 1,"labelname" : "购物性别","valueid" : 1,"valuename" : "女","order" : 1},{"labelid" : 1,"labelname" : "购物性别","valueid" : 2,"valuename" : "家庭","order" : 2}]},{"id" : 2,"name" : "会员级别","type" : 1,"order" : 2,"data" : [{"labelid" : 5,"labelname" : "会员级别","valueid" : 50,"valuename" : "注册会员","order" : 0},{"labelid" : 5,"labelname" : "会员级别","valueid" : 56,"valuename" : "铜牌会员","order" : 1},{"labelid" : 5,"labelname" : "会员级别","valueid" : 61,"valuename" : "银牌会员","order" : 2},{"labelid" : 5,"labelname" : "会员级别","valueid" : 62,"valuename" : "金牌会员","order" : 3},{"labelid" : 5,"labelname" : "会员级别","valueid" : 105,"valuename" : "钻石会员","order" : 4},{"labelid" : 5,"labelname" : "会员级别","valueid" : 110,"valuename" : "VIP","order" : 5}]},{"id" : 3,"name" : "连续活跃","type" : 2,"order" : 3,"data" : [{"labelid" : 3,"labelname" : "连续活跃","valueid" : 0,"valuename" : "否","order" : 0},{"labelid" : 3,"labelname" : "连续活跃","valueid" : 1,"valuename" : "是","order" : 1}]}]},{"id" : 2,"name" : "用户偏好","order" : 2,"data" : [{"id" : 4,"name" : "价格偏好","type" : 2,"order" : 1,"data" : [{"labelid" : 6,"labelname" : "价格偏好","valueid" : 1,"valuename" : "低","order" : 0},{"labelid" : 6,"labelname" : "价格偏好","valueid" : 2,"valuename" : "中","order" : 1},{"labelid" : 6,"labelname" : "价格偏好","valueid" : 3,"valuename" : "高","order" : 2},{"labelid" : 6,"labelname" : "价格偏好","valueid" : 4,"valuename" : "中高","order" : 3}]},{"id" : 5,"name" : "支付偏好","type" : 2,"order" : 2,"data" : [{"labelid" : 7,"labelname" : "支付偏好","valueid" : 1,"valuename" : "在线支付","order" : 0},{"labelid" : 7,"labelname" : "支付偏好","valueid" : 2,"valuename" : "货到付款","order" : 1}]},{"id" : 6,"name" : "行业偏好","type" : 3,"order" : 3,"data" : []}]},{"id" : 3,"name" : "行为轨迹","order" : 3,"data" : [{"id" : 7,"name" : "品牌行为","type" : 4,"order" : 1,"data" : []},{"id" : 8,"name" : "类目行为","type" : 5,"order" : 2,"data" : []}]},{"id" : 4,"name" : "广告偏好","order" : 4,"data" : [{"id" : 9,"name" : "广告偏好","type" : 1,"order" : 1,"data" : [{"labelid" : 62,"labelname" : "最近3天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近3天在京东全平台点击过广告","order" : 0},{"labelid" : 63,"labelname" : "最近7天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近7天在京东全平台点击过广告","order" : 0},{"labelid" : 64,"labelname" : "最近15天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近15天在京东全平台点击过广告","order" : 0},{"labelid" : 65,"labelname" : "最近30天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近30天在京东全平台点击过广告","order" : 0},{"labelid" : 66,"labelname" : "最近90天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近90天在京东全平台点击过广告","order" : 0},{"labelid" : 67,"labelname" : "最近180天在京东全平台点击过广告","valueid" : 0,"valuename" : "最近180天在京东全平台点击过广告","order" : 0}]}]}]}';

$j1 = json_encode($j);

var_dump($j1);
var_dump();
$s = json_decode($j1);
var_dump($s);
?>
