include $(EXPRESS_BASE_PATH)/makefile.comm

MY_LIBS = -ladutil

MY_INCS = -I${PLATFORM_BASE_PATH}/common/util/include/ \

OUTPUT = test_openfile

all:$(OUTPUT)

test_openfile:test_openfile.o

clean:
	rm -f *.o *.a $(OUTPUT) *pb.cc *pb.h